apiVersion: karo.io/v1alpha1
kind: AlertReaction
metadata:
  name: webhook-alert-reaction
  namespace: monitoring
spec:
  alertName: HighCPUUsage
  actions:
  - name: send-webhook
    image: dudizimber/karo-reactions-webhook-sender:v1.0.0
    env:
    - name: WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: webhook-config
          key: url
    - name: AUTH_HEADER
      valueFrom:
        secretKeyRef:
          name: webhook-config
          key: auth-header
    - name: TIMEOUT_SECONDS
      value: "30"
    - name: ALERT_JSON
      valueFrom:
        alertRef:
          fieldPath: "."
    - name: ALERT_NAME
      valueFrom:
        alertRef:
          fieldPath: "labels.alertname"
    - name: ALERT_STATUS
      valueFrom:
        alertRef:
          fieldPath: "status"
    - name: ALERT_SEVERITY
      valueFrom:
        alertRef:
          fieldPath: "labels.severity"
    - name: INSTANCE
      valueFrom:
        alertRef:
          fieldPath: "labels.instance"
    - name: ALERT_SUMMARY
      valueFrom:
        alertRef:
          fieldPath: "annotations.summary"
    - name: ALERT_DESCRIPTION
      valueFrom:
        alertRef:
          fieldPath: "annotations.description"
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "200m"
        memory: "64Mi"